// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tssotmorqcokbmnpyphu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzc290bW9ycWNva2JtbnB5cGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDgzOTIsImV4cCI6MjA3MDIyNDM5Mn0.SF8pSzqa6TL-cGzrVWOwE5Co9Kxmt5NAa3zHwlJUBbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});